import OpenAI from 'openai';
import { StateInfo } from '../types.js';
import { states as fallbackStates } from '../data/states.js';

const apiKey = process.env.OPENAI_API_KEY;
let client: OpenAI | null = null;

if (apiKey) {
  client = new OpenAI({ apiKey });
}

// ═══════════════════════════════════════════════
//  Indian states generated by OpenAI (cached)
// ═══════════════════════════════════════════════

let cachedStates: StateInfo[] | null = null;

async function generateStatesWithAI(): Promise<StateInfo[]> {
  if (!client) throw new Error('OPENAI_API_KEY not set');

  const completion = await client.chat.completions.create({
    model: 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content:
          'You are a geography expert. Return a JSON array of all 28 Indian states and 8 union territories.',
      },
      {
        role: 'user',
        content:
          'List every Indian state and union territory. For each, provide: name, abbreviation (2-letter ISO code), capital, latitude, longitude (capital coordinates). Return ONLY valid JSON as an array of objects with keys: name, abbreviation, capital, latitude, longitude.',
      },
    ],
    response_format: { type: 'json_object' },
    temperature: 0.1,
    max_tokens: 4000,
  });

  const text = completion.choices[0]?.message?.content;
  if (!text) throw new Error('OpenAI returned empty response');

  const parsed = JSON.parse(text) as
    | { states: StateInfo[] }
    | StateInfo[]
    | { [key: string]: StateInfo[] };

  let list: StateInfo[];

  if (Array.isArray(parsed)) {
    list = parsed;
  } else {
    const first = Object.values(parsed)[0];
    list = Array.isArray(first) ? first : [];
  }

  if (list.length < 30) {
    throw new Error(`OpenAI returned only ${list.length} entries — too few`);
  }

  return list.map((s) => ({
    name: String(s.name ?? ''),
    abbreviation: String(s.abbreviation ?? '').toUpperCase(),
    capital: String(s.capital ?? ''),
    latitude: Number(s.latitude),
    longitude: Number(s.longitude),
  }));
}

export async function getStates(): Promise<StateInfo[]> {
  if (cachedStates) return cachedStates;

  if (client) {
    try {
      cachedStates = await generateStatesWithAI();
      console.log(`✅ OpenAI generated ${cachedStates.length} states/UTs`);
      return cachedStates;
    } catch (err) {
      console.warn('⚠️  OpenAI states generation failed, using fallback:', (err as Error).message);
    }
  }

  cachedStates = fallbackStates;
  console.log(`📦 Using fallback data: ${cachedStates.length} states/UTs`);
  return cachedStates;
}

// ═══════════════════════════════════════════════
//  Real-time weather summary via OpenAI
// ═══════════════════════════════════════════════

export async function generateWeatherSummary(
  stateName: string,
  capital: string,
  hourly: { time: string; temperature: number; apparentTemperature: number; humidity: number; precipitationProbability: number; weatherCode: number }[],
): Promise<string | null> {
  if (!client) return null;

  const current = hourly[0]!;
  const highs = hourly.map((h) => h.temperature);
  const maxTemp = Math.max(...highs);
  const minTemp = Math.min(...highs);
  const avgPrecip = hourly.reduce((s, h) => s + h.precipitationProbability, 0) / hourly.length;

  const prompt = `Write a 2-3 sentence weather report for ${capital}, ${stateName}, India.
Current: ${current.temperature}°C (feels like ${current.apparentTemperature}°C), humidity ${current.humidity}%, precipitation chance ${current.precipitationProbability}%.
Today's range: ${minTemp}°C – ${maxTemp}°C, average rain probability ${avgPrecip.toFixed(0)}%.
Weather code: ${current.weatherCode} (0=clear, 1-3=cloudy, 45-48=fog, 51-67=drizzle/rain, 71-77=snow, 80-86=showers, 95-99=thunderstorm).

Keep it concise, informative, and natural. Do not mention the weather codes or data sources. End with a brief recommendation (e.g., take an umbrella, enjoy the sun, etc.).`;

  try {
    const completion = await client.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: 'You are a professional meteorologist. Write clear, concise weather reports.' },
        { role: 'user', content: prompt },
      ],
      temperature: 0.7,
      max_tokens: 300,
    });

    return completion.choices[0]?.message?.content?.trim() ?? null;
  } catch (err) {
    console.warn('⚠️  OpenAI weather summary failed:', (err as Error).message);
    return null;
  }
}
